name: Code compliance

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint flake8 isort
        python -m pip install numpy matplotlib PyYAML
    - name: Checking imports
      continue-on-error: false
      run: |
        isort --check $(git ls-files "*.py")
    - name: Check syntax
      continue-on-error: true
      run: |
        flake8 $(git ls-files '*.py')
    - name: Analysing code with pylint
      continue-on-error: true
      run: |
        for file in $(git ls-files '*.py'); do pylint $file; done
